apiVersion: v2
name: service
description: A generic Helm chart for deploying microservices
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - microservice
  - generic
  - bazel
maintainers:
  - name: test-forge-v2 Team
